version: '3'
services:

  app:
    # 直接指定路徑 build: ~/docker
    build:
      context: $HOME/docker
      dockerfile: $HOME/Github/o-p/docker/Dockerfile
      args:
        DEBUG: "false"
        USER: "root"
    image: app:latest # 自行命名
    container_name: web-app
    labels:
      com.kkinternal.description: "所有容器都可以取得此標籤"
    networks:
      - internal
    ports:
      - "9487:80"
    volumes:
      - .:/app


  db:
    image: "mysql:5.7.22"
    container_name: mysql57
    volumes:
      - mysql57:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
    networks:
      - internal
    ports:
      - "6033:3306/tcp" # 讓 local 可以直接操作 DB

  redis:
    image: "redis:4.0.10"
    container_name: redis4
    volumes:
      - redis4:/data
    ports:
      - "6379:6379" # as redis default

networks:
  internal: # connect between machines

volumes:
  mysql57:
  redis4:
